development:
  adapter: postgresql
  username: postgres
  password: kokakola1
  host: localhost
  database: Praca_inz_dev
  ool: 5
  timeout: 5000


test:
  adapter: postgresql
  username: postgres
  password: kokakola1
  host: localhost
  database: Praca_inz_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  username: ENV["POSTGRES_USERNAME"]
  password: ENV["POSTGRES_PASSWORD"]
  database: Praca_inz_prod
  pool: 5
  timeout: 5000
